- name: NGINX Ingress | Check if outputss dir exists
  stat: "path={{ role_path }}/outputs"
  register: outputs_dir_exists

- name: NGINX Ingress | Make sure the known hosts dir exists
  file:
    path: "{{ role_path }}/outputs"
    state: directory
  when: not outputs_dir_exists.stat.exists

- name: NGINX Ingress | Define Templates
  set_fact:
    ingress_nginx_templates:
      - { name: 00-namespace, file: 00-namespace.yaml }

- name: NGINX Ingress | Create Templates
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ role_path }}/outputs/{{ item.file }}"
  with_items: "{{ ingress_nginx_templates }}"
  register: ingress_nginx_templates_output