- name: Bootstrap Local Settings
  hosts: localhost
  connection: local
  roles:
    - bootstrap-local

- name: Bootstrap Required Users
  hosts: all_kube_nodes
  remote_user: root
  gather_facts: no
  roles:
    - bootstrap-users

- name: Harden Kubernetes Nodes
  hosts: all_kube_nodes
  remote_user: deployer
  become: true
  roles:
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
  vars:
    sysctl_overwrite:
      net.ipv6.conf.all.disable_ipv6: 0

- name: Bootstrap Kubernetes Nodes
  hosts: all_kube_nodes
  remote_user: deployer
  become: true
  roles:
    - bootstrap-nodes