- name: Configure Local Settings
  hosts: localhost
  connection: local
  become: no
  roles:
    - { role: local/known-hosts, tags: local }

- name: Bootstrap Required Users
  hosts: all
  remote_user: root
  become: no
  gather_facts: no
  roles:
    - { role: bootstrap/users, tags: users }

- name: Harden Kubernetes Nodes
  hosts: all
  remote_user: deployer
  become: true
  roles:
    - { role: dev-sec.os-hardening, tags: hardening }
    - { role: dev-sec.ssh-hardening, tags: hardening }
  vars:
    sysctl_overwrite:
      net.ipv6.conf.all.disable_ipv6: 0

- name: Bootstrap Kubernetes Nodes
  hosts: all
  remote_user: deployer
  become: true
  roles:
    - { role: bootstrap/nodes, tags: nodes }

- name: Install Kubernetes
  become: true
  remote_user: deployer
  import_playbook: kubespray/cluster.yml
  tags: kubespray

- name: Download Kubectl Config
  hosts: kube-master
  remote_user: deployer
  become: true
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: local/kube-config, tags: local }

- name: Install Kubernetes Apps
  hosts: localhost
  connection: local
  become: no
  roles:
    - { role: kubernetes/apps/metallb, tags: apps }
    - { role: kubernetes/apps/ingress-nginx, tags: apps }
    - { role: kubernetes/apps/cert-manager, tags: apps }
    - { role: kubernetes/apps/weave-flux, tags: apps }
  tasks:
    - name: Execute Install Script
      command: "bash {{ playbook_dir }}/scripts/install_kubernetes_apps.sh"
      changed_when: false
      tags: apps

- name: Install Flux Deploy Key
  hosts: localhost
  connection: local
  become: no
  tags: apps
  tasks:
    - name: Get Flux Deploy Key
      command: fluxctl --k8s-fwd-ns fluxcd identity
      changed_when: false
      register: fluxctl_cmd
      check_mode: always

    - name: Add Flux Deploy Key to GitHub
      flux_deploy_key:
        repo: 'jrmcdonald/helm-charts'
        title: 'fluxcd'
        key: '{{ fluxctl_cmd.stdout }}'
        read_only: false
        replace: true
        token: '{{ github_token }}'
