- name: Build Terraform State Store
  hosts: localhost
  connection: local
  roles:
    - bootstrap-terraform-state

- name: Execute Terraform
  hosts: localhost
  connection: local
  roles:
    - bootstrap-terraform