- name: Ambassador | Define Namespace
  community.kubernetes.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ ambassador_namespace }}"
    wait: true

- name: Ambassador | Add Datawire Repository
  community.kubernetes.helm_repository:
    name: datawire
    repo_url: "https://getambassador.io"

- name: Ambassador | Deploy
  community.kubernetes.helm:
    name: ambassador
    chart_ref: datawire/ambassador
    release_namespace: "{{ ambassador_namespace }}"

- name: Ambassador | Define Deployment Templates
  set_fact:
    ambassador_deployment_templates:
      - { name: module, file: ambassador-module.yaml }
      - { name: host, file: ambassador-host.yaml }

- name: Ambassador | Apply Deployment Files
  community.kubernetes.k8s:
    state: present
    apply: yes
    namespace: "{{ ambassador_namespace }}"
    definition: "{{ lookup('template', item.file) }}"
  with_items: "{{ ambassador_deployment_templates }}"
