- name: Weave Flux | Define Namespace
  community.kubernetes.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ weave_flux_namespace }}"
    wait: true

- name: Weave Flux | Download CRD
  get_url:
    url: https://raw.githubusercontent.com/fluxcd/helm-operator/master/deploy/crds.yaml
    dest: files/weave-flux.crds.yaml

- name: Weave Flux | Apply CRD
  community.kubernetes.k8s:
    state: present
    apply: yes
    definition: "{{ lookup('file', 'weave-flux.crds.yaml') }}"

- name: Weave Flux | Add Fluxcd Repository
  community.kubernetes.helm_repository:
    name: fluxcd
    repo_url: "https://charts.fluxcd.io"

- name: Weave Flux | Deploy Flux
  community.kubernetes.helm:
    name: flux
    chart_ref: fluxcd/fluxcd
    release_namespace: "{{ weave_flux_namespace }}"
    values:
      git:
        url: git@github.com:jrmcdonald/helm-charts

- name: Weave Flux | Deploy Helm Operator
  community.kubernetes.helm:
    name: helm-operator
    chart_ref: fluxcd/helm-operator
    release_namespace: "{{ weave_flux_namespace }}"
    values:
      helm:
        versions: v3
      git:
        ssh:
          secretName: flux-git-deploy

- name: Get Flux Deploy Key
  command: fluxctl --k8s-fwd-ns fluxcd identity
  changed_when: false
  register: fluxctl_cmd
  check_mode: always

- name: Add Flux Deploy Key to GitHub
  flux_deploy_key:
    repo: 'jrmcdonald/helm-charts'
    title: 'fluxcd'
    key: '{{ fluxctl_cmd.stdout }}'
    read_only: false
    replace: true
    token: '{{ github_token }}'