---
## Ansible Vars
ansible_python_interpreter: /usr/bin/python3

## Terraform Vars
aws_state_bucket: qwyck-platform-terraform-state
aws_state_table: qwyck-platform-terraform-lock
aws_region: eu-west-1

terraform_state: present

## Hetzner Cloud Vars
hcloud_image: ubuntu-18.04
hcloud_location: nbg1

hcloud_ip_range: '172.16.0.0/12'
hcloud_subnet_ip_range: '172.16.0.0/24'

hcloud_master_count: 1
hcloud_master_type: cx11
hcloud_master_hostname_format: master-%d

hcloud_worker_count: 2
hcloud_worker_type: cx11
hcloud_worker_hostname_format: worker-%d

hcloud_ssh_keys:
  - "cardno:000611341223"
  - "jamie@ios"
  - "github-ci@qwyck.net"
  - "ansible@macbook"

## Cloudflare Vars
cloudflare_email: jamie.mcdonald@qwyck.net
cloudflare_domain: qwyck-cloud.co.uk

## Kubespray Vars
bin_dir: /usr/local/bin

etcd_data_dir: /var/lib/etcd
etcd_kubeadm_enabled: false

loadbalancer_apiserver_port: 6443
loadbalancer_apiserver_healthcheck_port: 8081

## Kubespray Docker Vars
docker_bin_dir: "/usr/bin"
docker_container_storage_setup: false
docker_daemon_graph: "/var/lib/docker"
docker_dns_servers_strict: false
docker_iptables_enabled: "false"
docker_log_opts: "--log-opt max-size=50m --log-opt max-file=5"
docker_rpm_keepcache: 0