- name: Metallb | Define Templates
  set_fact:
    metallb_templates:
      - { name: 00-namespace, file: 00-namespace.yaml }
      - { name: helm-values, file: values.yaml }

- name: Metallb | Create Templates
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ role_path }}/outputs/{{ item.file }}"
  with_items: "{{ metallb_templates }}"
  register: metallb_templates_output