- name: MetalLB | Define Namespace 
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ metallb_namespace }}"
    wait: true
    
- name: MetalLB | Add Stable Repository
  helm_repository:
    name: stable
    repo_url: "https://kubernetes-charts.storage.googleapis.com"

- name: MetalLB | Deploy
  helm:
    name: metallb
    chart_ref: stable/metallb
    release_namespace: "{{ metallb_namespace }}"
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"