- name: Sealed Secrets | Add Stable Repository
  community.kubernetes.helm_repository:
    name: stable
    repo_url: "https://kubernetes-charts.storage.googleapis.com"

- name: Sealed Secrets | Deploy
  community.kubernetes.helm:
    name: sealed-secrets
    chart_ref: stable/sealed-secrets
    release_namespace: kube-system