- name: Cert-Manager | Define Namespace
  community.kubernetes.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ cert_manager_namespace }}"
    wait: true

- name: Cert-Manager | Add Jetstack Repository
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Cert-Manager | Deploy
  community.kubernetes.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: "{{ cert_manager_namespace }}"
    wait: true
    values:
      installCRDs: true

- name: Cert-Manager | Define Issuer Templates
  set_fact:
    cert_manager_issuer_templates:
      - { name: staging-issuer, file: staging-issuer.yaml.j2 }
      - { name: prod-issuer, file: prod-issuer.yaml.j2 }

- name: Cert-Manager | Apply Issuer Templates
  community.kubernetes.k8s:
    state: present
    apply: yes
    namespace: "{{ cert_manager_namespace }}"
    definition: "{{ lookup('template', item.file) }}"
  with_items: "{{ cert_manager_issuer_templates }}"
