- name: Cert-Manager | Define Namespace 
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ cert_manager_namespace }}"
    wait: true

- name: Cert-Manager | Download CRD
  get_url:
    url: https://github.com/jetstack/cert-manager/releases/download/v0.14.2/cert-manager.crds.yaml
    dest: files/cert-manager.crds.yaml

- name: Cert-Manager | Apply CRD
  k8s:
    state: present
    apply: yes
    definition: "{{ lookup('file', 'cert-manager.crds.yaml') }}"
    
- name: Cert-Manager | Add Jetstack Repository
  helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Cert-Manager | Deploy
  helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: "{{ cert_manager_namespace }}"
    
- name: Cert-Manager | Define Issuer Templates
  set_fact:
    cert_manager_issuer_templates:
      - { name: staging-issuer, file: staging-issuer.yaml }
      - { name: prod-issuer, file: prod-issuer.yaml }

- name: Cert-Manager | Apply Issuer Templates
  k8s:
    state: present
    apply: yes
    namespace: "{{ cert_manager_namespace }}"
    definition: "{{ lookup('templates', {{ item.file }}) }}"
    with_items: "{{ cert_manager_issuer_templates }}"
