- name: Cert-Manager | Check if outputss dir exists
  stat: "path={{ role_path }}/outputs"
  register: outputs_dir_exists

- name: Cert-Manager | Make sure the known hosts dir exists
  file:
    path: "{{ role_path }}/outputs"
    state: directory
  when: not outputs_dir_exists.stat.exists

- name: Cert-Manager | Define Templates
  set_fact:
    cert_manager_templates:
      - { name: 00-namespace, file: 00-namespace.yaml }
      - { name: staging-issuer, file: staging-issuer.yaml }
      - { name: prod-issuer, file: prod-issuer.yaml }

- name: Cert-Manager | Create Templates
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ role_path }}/outputs/{{ item.file }}"
  with_items: "{{ cert_manager_templates }}"
  register: cert_manager_templates_output