name: build

on:
  push:
    branches:
      - 'master'

env:
  tf_version: 'latest'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: postdeploy
        uses: jrmcdonald/blackbox-github-actions@v0.2.0
        with:
          bb_actions_subcommand: 'postdeploy'
        env:
          BLACKBOX_PUBKEY: ${{ secrets.CI_GPG_PUBKEY }}
          BLACKBOX_PRIVKEY: ${{ secrets.CI_GPG_SUBKEY }}
          
      - name: init
        uses: jrmcdonald/terraform-github-actions@v0.2.2
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'init'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_CLI_ARGS: "--var-file=secrets.tfvars.json"
          
      - name: apply
        uses: jrmcdonald/terraform-github-actions@v0.2.2
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'apply'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_PRIVKEY: ${{ secrets.CI_SSH_PRIVKEY }}
          TF_CLI_ARGS: "--var-file=secrets.tfvars.json"

      - name: shred
        uses: jrmcdonald/blackbox-github-actions@v0.2.0
        if: always()
        with:
          bb_actions_subcommand: 'shred_all_files'
        env:
          BLACKBOX_PUBKEY: ${{ secrets.CI_GPG_PUBKEY }}
          BLACKBOX_PRIVKEY: ${{ secrets.CI_GPG_SUBKEY }}
          
      - uses: actions/upload-artifact@v1
        with:
          name: kubeconfig
          path: ${HOME}/.kube
