name: build

on:
  - pull_request
  
jobs:
  terraform:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
          
      - name: fmt
        uses: jrmcdonald/terraform-github-actions@v0.1.0
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: init
        uses: jrmcdonald/terraform-github-actions@v0.1.0
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_TOKEN }}
          
      - name: validate
        uses: jrmcdonald/terraform-github-actions@v0.1.0
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: plan
        uses: jrmcdonald/terraform-github-actions@v0.1.0
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_TOKEN }}