name: build

on:
  - pull_request

jobs:
  terraform:

    env:
      GNUPGHOME: "${GITHUB_WORKSPACE}/.gnupg"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: debugging
        run: |
          pwd
          ll ${GITHUB_WORKSPACE}
          ll $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          mkdir .gnupg

      - name: gpg import public key
        run: echo -e "${{ secrets.CI_GPG_PUBKEY }}" | gpg --import

      - name: gpg import public key
        run: echo -e "${{ secrets.CI_GPG_SUBKEY }}" | gpg --import

      - name: gpg list keys
        run: gpg --list-keys

      - name: gpg list keys
        run: gpg --list-secret-keys

      - name: postdeploy
        uses: jrmcdonald/blackbox-github-actions@v0.1.0
        with:
          bb_actions_subcommand: 'postdeploy'

      - name: fmt
        uses: jrmcdonald/terraform-github-actions@v0.1.0
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: init
        uses: jrmcdonald/terraform-github-actions@v0.1.0
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_CLI_ARGS: "--var-file=secrets.tfvars.json"

      - name: validate
        uses: jrmcdonald/terraform-github-actions@v0.1.0
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: plan
        uses: jrmcdonald/terraform-github-actions@v0.1.0
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_CLI_ARGS: "--var-file=secrets.tfvars.json"

      - name: shred
        uses: jrmcdonald/blackbox-github-actions@v0.1.0
        with:
          bb_actions_subcommand: 'shred_all_files'